# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='backend.Area')),
            ],
        ),
    ]
