# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
