# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_church_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField()),
                ('time', models.TimeField()),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masses', to='backend.Church')),
            ],
        ),
    ]
